# Docker Compose v2 không cần version

services:
  spa-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: yumi-spa-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - spa-network

  # Uncomment nếu có backend API
  # backend:
  #   image: your-backend-image
  #   container_name: yumi-spa-backend
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #     - spa-network

networks:
  spa-network:
    driver: bridge

volumes:
  nginx-logs:
    driver: local